#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=28g,walltime=18:00:00
#PBS -N tractqc

time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main

#trying to workaround the issue of 
# -- Could not access the MATLAB Runtime component cache. Details: fl:filesystem:NotDirectoryError


